# Generated by Django 6.0 on 2025-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('vibration', models.IntegerField(blank=True, null=True)),
                ('raw_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
