# Generated by Django 6.0 on 2026-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('impact', models.FloatField()),
                ('vibration', models.BooleanField()),
                ('distance', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AccidentEvent',
        ),
    ]
